name: lint, build, deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  lint-build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn validate

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: github.ref == 'refs/heads/main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: github.ref == 'refs/heads/main'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ github.repository }}:latest
